### ISSUE TITLE
Chabge text on main page

### ISSUE THREAD

**Issue by plant7403** [isaksolheim/cyberscape#8]
Hi, can't find any way to nicesly change the content of the main page
Can see only an HTML page in the theme, but I'm not sure I want to edit the theme just for that

And in general, are there Hugo options to change like the logo

**Comment by isaksolheim** [comment]
Hi @plant7403 , the theme is not actively maintained, you can go ahead and modify the HTML in the theme directly! That is how I intended it being used

**Comment by plant7403** [comment]
I actually remembered how to do this
Like copying the file from the themes to the root directory
